allowBuilds:
  '@clerk/shared': set this to true or false
  '@parcel/watcher': set this to true or false
  '@percy/core': set this to true or false
  esbuild: set this to true or false
  onnxruntime-node: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@percy/core'
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - unrs-resolver
