allowBuilds:
  '@clerk/shared': false
  '@parcel/watcher': false
  '@percy/core': false
  esbuild: false
  msgpackr-extract: true
  onnxruntime-node: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@edd_remonts/ai-schadcn-chat@0.2.2 || 0.2.3 || 0.2.4 || 0.3.0 || 0.3.1'
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@percy/core'
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - unrs-resolver
