/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LandingDocsRouteImport } from './routes/_landing/_docs'
import { Route as DashboardDashboardRouteRouteImport } from './routes/_dashboard/dashboard/route'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiTestConnectionRouteImport } from './routes/api/ai/test-connection'
import { Route as ApiAiStatusRouteImport } from './routes/api/ai/status'
import { Route as ApiAiSearchRouteImport } from './routes/api/ai/search'
import { Route as ApiAiModelsRouteImport } from './routes/api/ai/models'
import { Route as ApiAiConfigStoreRouteImport } from './routes/api/ai/config-store'
import { Route as ApiAiAuditRouteImport } from './routes/api/ai/audit'
import { Route as LandingDocsDocsRouteImport } from './routes/_landing/_docs/docs'
import { Route as DashboardDashboardUsersRouteImport } from './routes/_dashboard/dashboard/users'
import { Route as DashboardDashboardHelpRouteImport } from './routes/_dashboard/dashboard/help'
import { Route as DashboardDashboardContactMessagesRouteImport } from './routes/_dashboard/dashboard/contact-messages'
import { Route as ApiAiChatRouteRouteImport } from './routes/api/ai/chat/route'
import { Route as DashboardDashboardSettingsRouteRouteImport } from './routes/_dashboard/dashboard/settings/route'
import { Route as DashboardDashboardSettingsIndexRouteImport } from './routes/_dashboard/dashboard/settings/index'
import { Route as ApiAiChatCompletionsRouteImport } from './routes/api/ai/chat/completions'
import { Route as LandingDocsSupportGuidesRouteImport } from './routes/_landing/_docs/support/guides'
import { Route as LandingDocsSupportFaqRouteImport } from './routes/_landing/_docs/support/faq'
import { Route as LandingDocsSupportExamplesRouteImport } from './routes/_landing/_docs/support/examples'
import { Route as LandingDocsSupportDocumentationRouteImport } from './routes/_landing/_docs/support/documentation'
import { Route as LandingDocsStarterModuleMapRouteImport } from './routes/_landing/_docs/starter/module-map'
import { Route as LandingDocsStarterDesignTokensRouteImport } from './routes/_landing/_docs/starter/design-tokens'
import { Route as LandingDocsStarterConventionsRouteImport } from './routes/_landing/_docs/starter/conventions'
import { Route as LandingDocsStarterArchitectureRouteImport } from './routes/_landing/_docs/starter/architecture'
import { Route as LandingDocsProductRoadmapRouteImport } from './routes/_landing/_docs/product/roadmap'
import { Route as LandingDocsProductReleaseNotesRouteImport } from './routes/_landing/_docs/product/release-notes'
import { Route as LandingDocsProductIntegrationsRouteImport } from './routes/_landing/_docs/product/integrations'
import { Route as LandingDocsProductChangelogRouteImport } from './routes/_landing/_docs/product/changelog'
import { Route as LandingDocsLegalTermsRouteImport } from './routes/_landing/_docs/legal/terms'
import { Route as LandingDocsLegalPrivacyRouteImport } from './routes/_landing/_docs/legal/privacy'
import { Route as LandingDocsLegalLicensesRouteImport } from './routes/_landing/_docs/legal/licenses'
import { Route as LandingDocsLegalCookiesRouteImport } from './routes/_landing/_docs/legal/cookies'
import { Route as DashboardDashboardSettingsSystemRouteImport } from './routes/_dashboard/dashboard/settings/system'
import { Route as DashboardDashboardSettingsIa_configRouteImport } from './routes/_dashboard/dashboard/settings/ia_config'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingDocsRoute = LandingDocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => LandingRouteRoute,
} as any)
const DashboardDashboardRouteRoute = DashboardDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTestConnectionRoute = ApiAiTestConnectionRouteImport.update({
  id: '/api/ai/test-connection',
  path: '/api/ai/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai/status',
  path: '/api/ai/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSearchRoute = ApiAiSearchRouteImport.update({
  id: '/api/ai/search',
  path: '/api/ai/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiModelsRoute = ApiAiModelsRouteImport.update({
  id: '/api/ai/models',
  path: '/api/ai/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConfigStoreRoute = ApiAiConfigStoreRouteImport.update({
  id: '/api/ai/config-store',
  path: '/api/ai/config-store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAuditRoute = ApiAiAuditRouteImport.update({
  id: '/api/ai/audit',
  path: '/api/ai/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingDocsDocsRoute = LandingDocsDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => LandingDocsRoute,
} as any)
const DashboardDashboardUsersRoute = DashboardDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardDashboardRouteRoute,
} as any)
const DashboardDashboardHelpRoute = DashboardDashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardDashboardRouteRoute,
} as any)
const DashboardDashboardContactMessagesRoute =
  DashboardDashboardContactMessagesRouteImport.update({
    id: '/contact-messages',
    path: '/contact-messages',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const ApiAiChatRouteRoute = ApiAiChatRouteRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardSettingsRouteRoute =
  DashboardDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardSettingsIndexRoute =
  DashboardDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardSettingsRouteRoute,
  } as any)
const ApiAiChatCompletionsRoute = ApiAiChatCompletionsRouteImport.update({
  id: '/completions',
  path: '/completions',
  getParentRoute: () => ApiAiChatRouteRoute,
} as any)
const LandingDocsSupportGuidesRoute =
  LandingDocsSupportGuidesRouteImport.update({
    id: '/support/guides',
    path: '/support/guides',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsSupportFaqRoute = LandingDocsSupportFaqRouteImport.update({
  id: '/support/faq',
  path: '/support/faq',
  getParentRoute: () => LandingDocsRoute,
} as any)
const LandingDocsSupportExamplesRoute =
  LandingDocsSupportExamplesRouteImport.update({
    id: '/support/examples',
    path: '/support/examples',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsSupportDocumentationRoute =
  LandingDocsSupportDocumentationRouteImport.update({
    id: '/support/documentation',
    path: '/support/documentation',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsStarterModuleMapRoute =
  LandingDocsStarterModuleMapRouteImport.update({
    id: '/starter/module-map',
    path: '/starter/module-map',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsStarterDesignTokensRoute =
  LandingDocsStarterDesignTokensRouteImport.update({
    id: '/starter/design-tokens',
    path: '/starter/design-tokens',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsStarterConventionsRoute =
  LandingDocsStarterConventionsRouteImport.update({
    id: '/starter/conventions',
    path: '/starter/conventions',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsStarterArchitectureRoute =
  LandingDocsStarterArchitectureRouteImport.update({
    id: '/starter/architecture',
    path: '/starter/architecture',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsProductRoadmapRoute =
  LandingDocsProductRoadmapRouteImport.update({
    id: '/product/roadmap',
    path: '/product/roadmap',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsProductReleaseNotesRoute =
  LandingDocsProductReleaseNotesRouteImport.update({
    id: '/product/release-notes',
    path: '/product/release-notes',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsProductIntegrationsRoute =
  LandingDocsProductIntegrationsRouteImport.update({
    id: '/product/integrations',
    path: '/product/integrations',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsProductChangelogRoute =
  LandingDocsProductChangelogRouteImport.update({
    id: '/product/changelog',
    path: '/product/changelog',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsLegalTermsRoute = LandingDocsLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => LandingDocsRoute,
} as any)
const LandingDocsLegalPrivacyRoute = LandingDocsLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => LandingDocsRoute,
} as any)
const LandingDocsLegalLicensesRoute =
  LandingDocsLegalLicensesRouteImport.update({
    id: '/legal/licenses',
    path: '/legal/licenses',
    getParentRoute: () => LandingDocsRoute,
  } as any)
const LandingDocsLegalCookiesRoute = LandingDocsLegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => LandingDocsRoute,
} as any)
const DashboardDashboardSettingsSystemRoute =
  DashboardDashboardSettingsSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => DashboardDashboardSettingsRouteRoute,
  } as any)
const DashboardDashboardSettingsIa_configRoute =
  DashboardDashboardSettingsIa_configRouteImport.update({
    id: '/ia_config',
    path: '/ia_config',
    getParentRoute: () => DashboardDashboardSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardDashboardRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRouteRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRouteRouteWithChildren
  '/dashboard/contact-messages': typeof DashboardDashboardContactMessagesRoute
  '/dashboard/help': typeof DashboardDashboardHelpRoute
  '/dashboard/users': typeof DashboardDashboardUsersRoute
  '/docs': typeof LandingDocsDocsRoute
  '/api/ai/audit': typeof ApiAiAuditRoute
  '/api/ai/config-store': typeof ApiAiConfigStoreRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/settings/ia_config': typeof DashboardDashboardSettingsIa_configRoute
  '/dashboard/settings/system': typeof DashboardDashboardSettingsSystemRoute
  '/legal/cookies': typeof LandingDocsLegalCookiesRoute
  '/legal/licenses': typeof LandingDocsLegalLicensesRoute
  '/legal/privacy': typeof LandingDocsLegalPrivacyRoute
  '/legal/terms': typeof LandingDocsLegalTermsRoute
  '/product/changelog': typeof LandingDocsProductChangelogRoute
  '/product/integrations': typeof LandingDocsProductIntegrationsRoute
  '/product/release-notes': typeof LandingDocsProductReleaseNotesRoute
  '/product/roadmap': typeof LandingDocsProductRoadmapRoute
  '/starter/architecture': typeof LandingDocsStarterArchitectureRoute
  '/starter/conventions': typeof LandingDocsStarterConventionsRoute
  '/starter/design-tokens': typeof LandingDocsStarterDesignTokensRoute
  '/starter/module-map': typeof LandingDocsStarterModuleMapRoute
  '/support/documentation': typeof LandingDocsSupportDocumentationRoute
  '/support/examples': typeof LandingDocsSupportExamplesRoute
  '/support/faq': typeof LandingDocsSupportFaqRoute
  '/support/guides': typeof LandingDocsSupportGuidesRoute
  '/api/ai/chat/completions': typeof ApiAiChatCompletionsRoute
  '/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/api/ai/chat': typeof ApiAiChatRouteRouteWithChildren
  '/dashboard/contact-messages': typeof DashboardDashboardContactMessagesRoute
  '/dashboard/help': typeof DashboardDashboardHelpRoute
  '/dashboard/users': typeof DashboardDashboardUsersRoute
  '/docs': typeof LandingDocsDocsRoute
  '/api/ai/audit': typeof ApiAiAuditRoute
  '/api/ai/config-store': typeof ApiAiConfigStoreRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/settings/ia_config': typeof DashboardDashboardSettingsIa_configRoute
  '/dashboard/settings/system': typeof DashboardDashboardSettingsSystemRoute
  '/legal/cookies': typeof LandingDocsLegalCookiesRoute
  '/legal/licenses': typeof LandingDocsLegalLicensesRoute
  '/legal/privacy': typeof LandingDocsLegalPrivacyRoute
  '/legal/terms': typeof LandingDocsLegalTermsRoute
  '/product/changelog': typeof LandingDocsProductChangelogRoute
  '/product/integrations': typeof LandingDocsProductIntegrationsRoute
  '/product/release-notes': typeof LandingDocsProductReleaseNotesRoute
  '/product/roadmap': typeof LandingDocsProductRoadmapRoute
  '/starter/architecture': typeof LandingDocsStarterArchitectureRoute
  '/starter/conventions': typeof LandingDocsStarterConventionsRoute
  '/starter/design-tokens': typeof LandingDocsStarterDesignTokensRoute
  '/starter/module-map': typeof LandingDocsStarterModuleMapRoute
  '/support/documentation': typeof LandingDocsSupportDocumentationRoute
  '/support/examples': typeof LandingDocsSupportExamplesRoute
  '/support/faq': typeof LandingDocsSupportFaqRoute
  '/support/guides': typeof LandingDocsSupportGuidesRoute
  '/api/ai/chat/completions': typeof ApiAiChatCompletionsRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRouteRouteWithChildren
  '/_landing/_docs': typeof LandingDocsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_landing/': typeof LandingIndexRoute
  '/_dashboard/dashboard/settings': typeof DashboardDashboardSettingsRouteRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRouteRouteWithChildren
  '/_dashboard/dashboard/contact-messages': typeof DashboardDashboardContactMessagesRoute
  '/_dashboard/dashboard/help': typeof DashboardDashboardHelpRoute
  '/_dashboard/dashboard/users': typeof DashboardDashboardUsersRoute
  '/_landing/_docs/docs': typeof LandingDocsDocsRoute
  '/api/ai/audit': typeof ApiAiAuditRoute
  '/api/ai/config-store': typeof ApiAiConfigStoreRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/settings/ia_config': typeof DashboardDashboardSettingsIa_configRoute
  '/_dashboard/dashboard/settings/system': typeof DashboardDashboardSettingsSystemRoute
  '/_landing/_docs/legal/cookies': typeof LandingDocsLegalCookiesRoute
  '/_landing/_docs/legal/licenses': typeof LandingDocsLegalLicensesRoute
  '/_landing/_docs/legal/privacy': typeof LandingDocsLegalPrivacyRoute
  '/_landing/_docs/legal/terms': typeof LandingDocsLegalTermsRoute
  '/_landing/_docs/product/changelog': typeof LandingDocsProductChangelogRoute
  '/_landing/_docs/product/integrations': typeof LandingDocsProductIntegrationsRoute
  '/_landing/_docs/product/release-notes': typeof LandingDocsProductReleaseNotesRoute
  '/_landing/_docs/product/roadmap': typeof LandingDocsProductRoadmapRoute
  '/_landing/_docs/starter/architecture': typeof LandingDocsStarterArchitectureRoute
  '/_landing/_docs/starter/conventions': typeof LandingDocsStarterConventionsRoute
  '/_landing/_docs/starter/design-tokens': typeof LandingDocsStarterDesignTokensRoute
  '/_landing/_docs/starter/module-map': typeof LandingDocsStarterModuleMapRoute
  '/_landing/_docs/support/documentation': typeof LandingDocsSupportDocumentationRoute
  '/_landing/_docs/support/examples': typeof LandingDocsSupportExamplesRoute
  '/_landing/_docs/support/faq': typeof LandingDocsSupportFaqRoute
  '/_landing/_docs/support/guides': typeof LandingDocsSupportGuidesRoute
  '/api/ai/chat/completions': typeof ApiAiChatCompletionsRoute
  '/_dashboard/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/health'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/settings'
    | '/api/ai/chat'
    | '/dashboard/contact-messages'
    | '/dashboard/help'
    | '/dashboard/users'
    | '/docs'
    | '/api/ai/audit'
    | '/api/ai/config-store'
    | '/api/ai/models'
    | '/api/ai/search'
    | '/api/ai/status'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/dashboard/'
    | '/dashboard/settings/ia_config'
    | '/dashboard/settings/system'
    | '/legal/cookies'
    | '/legal/licenses'
    | '/legal/privacy'
    | '/legal/terms'
    | '/product/changelog'
    | '/product/integrations'
    | '/product/release-notes'
    | '/product/roadmap'
    | '/starter/architecture'
    | '/starter/conventions'
    | '/starter/design-tokens'
    | '/starter/module-map'
    | '/support/documentation'
    | '/support/examples'
    | '/support/faq'
    | '/support/guides'
    | '/api/ai/chat/completions'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/health'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/ai/chat'
    | '/dashboard/contact-messages'
    | '/dashboard/help'
    | '/dashboard/users'
    | '/docs'
    | '/api/ai/audit'
    | '/api/ai/config-store'
    | '/api/ai/models'
    | '/api/ai/search'
    | '/api/ai/status'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/dashboard'
    | '/dashboard/settings/ia_config'
    | '/dashboard/settings/system'
    | '/legal/cookies'
    | '/legal/licenses'
    | '/legal/privacy'
    | '/legal/terms'
    | '/product/changelog'
    | '/product/integrations'
    | '/product/release-notes'
    | '/product/roadmap'
    | '/starter/architecture'
    | '/starter/conventions'
    | '/starter/design-tokens'
    | '/starter/module-map'
    | '/support/documentation'
    | '/support/examples'
    | '/support/faq'
    | '/support/guides'
    | '/api/ai/chat/completions'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_landing'
    | '/auth'
    | '/_dashboard/dashboard'
    | '/_landing/_docs'
    | '/api/health'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_landing/'
    | '/_dashboard/dashboard/settings'
    | '/api/ai/chat'
    | '/_dashboard/dashboard/contact-messages'
    | '/_dashboard/dashboard/help'
    | '/_dashboard/dashboard/users'
    | '/_landing/_docs/docs'
    | '/api/ai/audit'
    | '/api/ai/config-store'
    | '/api/ai/models'
    | '/api/ai/search'
    | '/api/ai/status'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/settings/ia_config'
    | '/_dashboard/dashboard/settings/system'
    | '/_landing/_docs/legal/cookies'
    | '/_landing/_docs/legal/licenses'
    | '/_landing/_docs/legal/privacy'
    | '/_landing/_docs/legal/terms'
    | '/_landing/_docs/product/changelog'
    | '/_landing/_docs/product/integrations'
    | '/_landing/_docs/product/release-notes'
    | '/_landing/_docs/product/roadmap'
    | '/_landing/_docs/starter/architecture'
    | '/_landing/_docs/starter/conventions'
    | '/_landing/_docs/starter/design-tokens'
    | '/_landing/_docs/starter/module-map'
    | '/_landing/_docs/support/documentation'
    | '/_landing/_docs/support/examples'
    | '/_landing/_docs/support/faq'
    | '/_landing/_docs/support/guides'
    | '/api/ai/chat/completions'
    | '/_dashboard/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAiChatRouteRoute: typeof ApiAiChatRouteRouteWithChildren
  ApiAiAuditRoute: typeof ApiAiAuditRoute
  ApiAiConfigStoreRoute: typeof ApiAiConfigStoreRoute
  ApiAiModelsRoute: typeof ApiAiModelsRoute
  ApiAiSearchRoute: typeof ApiAiSearchRoute
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiAiTestConnectionRoute: typeof ApiAiTestConnectionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/_docs': {
      id: '/_landing/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingDocsRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/test-connection': {
      id: '/api/ai/test-connection'
      path: '/api/ai/test-connection'
      fullPath: '/api/ai/test-connection'
      preLoaderRoute: typeof ApiAiTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/status': {
      id: '/api/ai/status'
      path: '/api/ai/status'
      fullPath: '/api/ai/status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/search': {
      id: '/api/ai/search'
      path: '/api/ai/search'
      fullPath: '/api/ai/search'
      preLoaderRoute: typeof ApiAiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/models': {
      id: '/api/ai/models'
      path: '/api/ai/models'
      fullPath: '/api/ai/models'
      preLoaderRoute: typeof ApiAiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/config-store': {
      id: '/api/ai/config-store'
      path: '/api/ai/config-store'
      fullPath: '/api/ai/config-store'
      preLoaderRoute: typeof ApiAiConfigStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/audit': {
      id: '/api/ai/audit'
      path: '/api/ai/audit'
      fullPath: '/api/ai/audit'
      preLoaderRoute: typeof ApiAiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/_docs/docs': {
      id: '/_landing/_docs/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof LandingDocsDocsRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_dashboard/dashboard/users': {
      id: '/_dashboard/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardDashboardUsersRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/help': {
      id: '/_dashboard/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardDashboardHelpRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/contact-messages': {
      id: '/_dashboard/dashboard/contact-messages'
      path: '/contact-messages'
      fullPath: '/dashboard/contact-messages'
      preLoaderRoute: typeof DashboardDashboardContactMessagesRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/settings/': {
      id: '/_dashboard/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardDashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardDashboardSettingsRouteRoute
    }
    '/api/ai/chat/completions': {
      id: '/api/ai/chat/completions'
      path: '/completions'
      fullPath: '/api/ai/chat/completions'
      preLoaderRoute: typeof ApiAiChatCompletionsRouteImport
      parentRoute: typeof ApiAiChatRouteRoute
    }
    '/_landing/_docs/support/guides': {
      id: '/_landing/_docs/support/guides'
      path: '/support/guides'
      fullPath: '/support/guides'
      preLoaderRoute: typeof LandingDocsSupportGuidesRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/support/faq': {
      id: '/_landing/_docs/support/faq'
      path: '/support/faq'
      fullPath: '/support/faq'
      preLoaderRoute: typeof LandingDocsSupportFaqRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/support/examples': {
      id: '/_landing/_docs/support/examples'
      path: '/support/examples'
      fullPath: '/support/examples'
      preLoaderRoute: typeof LandingDocsSupportExamplesRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/support/documentation': {
      id: '/_landing/_docs/support/documentation'
      path: '/support/documentation'
      fullPath: '/support/documentation'
      preLoaderRoute: typeof LandingDocsSupportDocumentationRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/starter/module-map': {
      id: '/_landing/_docs/starter/module-map'
      path: '/starter/module-map'
      fullPath: '/starter/module-map'
      preLoaderRoute: typeof LandingDocsStarterModuleMapRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/starter/design-tokens': {
      id: '/_landing/_docs/starter/design-tokens'
      path: '/starter/design-tokens'
      fullPath: '/starter/design-tokens'
      preLoaderRoute: typeof LandingDocsStarterDesignTokensRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/starter/conventions': {
      id: '/_landing/_docs/starter/conventions'
      path: '/starter/conventions'
      fullPath: '/starter/conventions'
      preLoaderRoute: typeof LandingDocsStarterConventionsRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/starter/architecture': {
      id: '/_landing/_docs/starter/architecture'
      path: '/starter/architecture'
      fullPath: '/starter/architecture'
      preLoaderRoute: typeof LandingDocsStarterArchitectureRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/product/roadmap': {
      id: '/_landing/_docs/product/roadmap'
      path: '/product/roadmap'
      fullPath: '/product/roadmap'
      preLoaderRoute: typeof LandingDocsProductRoadmapRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/product/release-notes': {
      id: '/_landing/_docs/product/release-notes'
      path: '/product/release-notes'
      fullPath: '/product/release-notes'
      preLoaderRoute: typeof LandingDocsProductReleaseNotesRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/product/integrations': {
      id: '/_landing/_docs/product/integrations'
      path: '/product/integrations'
      fullPath: '/product/integrations'
      preLoaderRoute: typeof LandingDocsProductIntegrationsRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/product/changelog': {
      id: '/_landing/_docs/product/changelog'
      path: '/product/changelog'
      fullPath: '/product/changelog'
      preLoaderRoute: typeof LandingDocsProductChangelogRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/legal/terms': {
      id: '/_landing/_docs/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LandingDocsLegalTermsRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/legal/privacy': {
      id: '/_landing/_docs/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LandingDocsLegalPrivacyRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/legal/licenses': {
      id: '/_landing/_docs/legal/licenses'
      path: '/legal/licenses'
      fullPath: '/legal/licenses'
      preLoaderRoute: typeof LandingDocsLegalLicensesRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_landing/_docs/legal/cookies': {
      id: '/_landing/_docs/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LandingDocsLegalCookiesRouteImport
      parentRoute: typeof LandingDocsRoute
    }
    '/_dashboard/dashboard/settings/system': {
      id: '/_dashboard/dashboard/settings/system'
      path: '/system'
      fullPath: '/dashboard/settings/system'
      preLoaderRoute: typeof DashboardDashboardSettingsSystemRouteImport
      parentRoute: typeof DashboardDashboardSettingsRouteRoute
    }
    '/_dashboard/dashboard/settings/ia_config': {
      id: '/_dashboard/dashboard/settings/ia_config'
      path: '/ia_config'
      fullPath: '/dashboard/settings/ia_config'
      preLoaderRoute: typeof DashboardDashboardSettingsIa_configRouteImport
      parentRoute: typeof DashboardDashboardSettingsRouteRoute
    }
  }
}

interface DashboardDashboardSettingsRouteRouteChildren {
  DashboardDashboardSettingsIa_configRoute: typeof DashboardDashboardSettingsIa_configRoute
  DashboardDashboardSettingsSystemRoute: typeof DashboardDashboardSettingsSystemRoute
  DashboardDashboardSettingsIndexRoute: typeof DashboardDashboardSettingsIndexRoute
}

const DashboardDashboardSettingsRouteRouteChildren: DashboardDashboardSettingsRouteRouteChildren =
  {
    DashboardDashboardSettingsIa_configRoute:
      DashboardDashboardSettingsIa_configRoute,
    DashboardDashboardSettingsSystemRoute:
      DashboardDashboardSettingsSystemRoute,
    DashboardDashboardSettingsIndexRoute: DashboardDashboardSettingsIndexRoute,
  }

const DashboardDashboardSettingsRouteRouteWithChildren =
  DashboardDashboardSettingsRouteRoute._addFileChildren(
    DashboardDashboardSettingsRouteRouteChildren,
  )

interface DashboardDashboardRouteRouteChildren {
  DashboardDashboardSettingsRouteRoute: typeof DashboardDashboardSettingsRouteRouteWithChildren
  DashboardDashboardContactMessagesRoute: typeof DashboardDashboardContactMessagesRoute
  DashboardDashboardHelpRoute: typeof DashboardDashboardHelpRoute
  DashboardDashboardUsersRoute: typeof DashboardDashboardUsersRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
}

const DashboardDashboardRouteRouteChildren: DashboardDashboardRouteRouteChildren =
  {
    DashboardDashboardSettingsRouteRoute:
      DashboardDashboardSettingsRouteRouteWithChildren,
    DashboardDashboardContactMessagesRoute:
      DashboardDashboardContactMessagesRoute,
    DashboardDashboardHelpRoute: DashboardDashboardHelpRoute,
    DashboardDashboardUsersRoute: DashboardDashboardUsersRoute,
    DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  }

const DashboardDashboardRouteRouteWithChildren =
  DashboardDashboardRouteRoute._addFileChildren(
    DashboardDashboardRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardDashboardRouteRoute: typeof DashboardDashboardRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardRouteRoute: DashboardDashboardRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LandingDocsRouteChildren {
  LandingDocsDocsRoute: typeof LandingDocsDocsRoute
  LandingDocsLegalCookiesRoute: typeof LandingDocsLegalCookiesRoute
  LandingDocsLegalLicensesRoute: typeof LandingDocsLegalLicensesRoute
  LandingDocsLegalPrivacyRoute: typeof LandingDocsLegalPrivacyRoute
  LandingDocsLegalTermsRoute: typeof LandingDocsLegalTermsRoute
  LandingDocsProductChangelogRoute: typeof LandingDocsProductChangelogRoute
  LandingDocsProductIntegrationsRoute: typeof LandingDocsProductIntegrationsRoute
  LandingDocsProductReleaseNotesRoute: typeof LandingDocsProductReleaseNotesRoute
  LandingDocsProductRoadmapRoute: typeof LandingDocsProductRoadmapRoute
  LandingDocsStarterArchitectureRoute: typeof LandingDocsStarterArchitectureRoute
  LandingDocsStarterConventionsRoute: typeof LandingDocsStarterConventionsRoute
  LandingDocsStarterDesignTokensRoute: typeof LandingDocsStarterDesignTokensRoute
  LandingDocsStarterModuleMapRoute: typeof LandingDocsStarterModuleMapRoute
  LandingDocsSupportDocumentationRoute: typeof LandingDocsSupportDocumentationRoute
  LandingDocsSupportExamplesRoute: typeof LandingDocsSupportExamplesRoute
  LandingDocsSupportFaqRoute: typeof LandingDocsSupportFaqRoute
  LandingDocsSupportGuidesRoute: typeof LandingDocsSupportGuidesRoute
}

const LandingDocsRouteChildren: LandingDocsRouteChildren = {
  LandingDocsDocsRoute: LandingDocsDocsRoute,
  LandingDocsLegalCookiesRoute: LandingDocsLegalCookiesRoute,
  LandingDocsLegalLicensesRoute: LandingDocsLegalLicensesRoute,
  LandingDocsLegalPrivacyRoute: LandingDocsLegalPrivacyRoute,
  LandingDocsLegalTermsRoute: LandingDocsLegalTermsRoute,
  LandingDocsProductChangelogRoute: LandingDocsProductChangelogRoute,
  LandingDocsProductIntegrationsRoute: LandingDocsProductIntegrationsRoute,
  LandingDocsProductReleaseNotesRoute: LandingDocsProductReleaseNotesRoute,
  LandingDocsProductRoadmapRoute: LandingDocsProductRoadmapRoute,
  LandingDocsStarterArchitectureRoute: LandingDocsStarterArchitectureRoute,
  LandingDocsStarterConventionsRoute: LandingDocsStarterConventionsRoute,
  LandingDocsStarterDesignTokensRoute: LandingDocsStarterDesignTokensRoute,
  LandingDocsStarterModuleMapRoute: LandingDocsStarterModuleMapRoute,
  LandingDocsSupportDocumentationRoute: LandingDocsSupportDocumentationRoute,
  LandingDocsSupportExamplesRoute: LandingDocsSupportExamplesRoute,
  LandingDocsSupportFaqRoute: LandingDocsSupportFaqRoute,
  LandingDocsSupportGuidesRoute: LandingDocsSupportGuidesRoute,
}

const LandingDocsRouteWithChildren = LandingDocsRoute._addFileChildren(
  LandingDocsRouteChildren,
)

interface LandingRouteRouteChildren {
  LandingDocsRoute: typeof LandingDocsRouteWithChildren
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingDocsRoute: LandingDocsRouteWithChildren,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ApiAiChatRouteRouteChildren {
  ApiAiChatCompletionsRoute: typeof ApiAiChatCompletionsRoute
}

const ApiAiChatRouteRouteChildren: ApiAiChatRouteRouteChildren = {
  ApiAiChatCompletionsRoute: ApiAiChatCompletionsRoute,
}

const ApiAiChatRouteRouteWithChildren = ApiAiChatRouteRoute._addFileChildren(
  ApiAiChatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAiChatRouteRoute: ApiAiChatRouteRouteWithChildren,
  ApiAiAuditRoute: ApiAiAuditRoute,
  ApiAiConfigStoreRoute: ApiAiConfigStoreRoute,
  ApiAiModelsRoute: ApiAiModelsRoute,
  ApiAiSearchRoute: ApiAiSearchRoute,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiAiTestConnectionRoute: ApiAiTestConnectionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
